# Generated by Django 5.2.17 on 2026-09-09 12:42

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('conversations', '0002_customer_email_customer_phone'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProfileNumberCounter',
            fields=[
                ('id', models.PositiveSmallIntegerField(default=1, editable=False, primary_key=True, serialize=False)),
                ('last_number', models.PositiveIntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='TravelProfile',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('profile_number', models.CharField(blank=True, help_text='BP-000123; assigned automatically when the first detail is captured.', max_length=20, unique=True)),
                ('full_name', models.CharField(blank=True, max_length=120)),
                ('whatsapp_number', models.CharField(blank=True, max_length=32)),
                ('nationality', models.CharField(blank=True, max_length=80)),
                ('residence_country', models.CharField(blank=True, max_length=80)),
                ('gcc_residence_card', models.BooleanField(blank=True, help_text='Unknown until the visitor answers.', null=True)),
                ('residence_card_expiry', models.DateField(blank=True, null=True)),
                ('travel_date', models.DateField(blank=True, null=True)),
                ('trip_days', models.PositiveIntegerField(blank=True, null=True)),
                ('adults', models.PositiveIntegerField(blank=True, help_text='Number of adult travellers.', null=True)),
                ('children_ages', models.CharField(blank=True, help_text="Comma-separated ages, e.g. '5, 8'.", max_length=120)),
                ('is_complete', models.BooleanField(default=False)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('customer', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='travel_profile', to='conversations.customer')),
            ],
            options={
                'ordering': ['-updated_at'],
            },
        ),
    ]
