# Generated by Django 5.2.17 on 2026-09-10 05:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='travelprofile',
            name='questions_sent_at',
            field=models.DateTimeField(blank=True, help_text='When the scripted profile questions were sent — they are asked only once.', null=True),
        ),
        migrations.AddField(
            model_name='travelprofile',
            name='travel_intent_detected',
            field=models.BooleanField(default=False, help_text="Set once the visitor's messages show travel interest (keyword match or LLM detection); gates the scripted profile questions."),
        ),
    ]
