# Generated by Django 5.2.11 on 2026-09-04 17:26

import pgvector.django.vector
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.RunSQL(
            sql='CREATE EXTENSION IF NOT EXISTS vector;',
            reverse_sql='DROP EXTENSION IF EXISTS vector;',
        ),
        migrations.CreateModel(
            name='BotSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fallback_message', models.TextField(help_text='Sent when the bot has low/no confidence, e.g. "I\'m not sure about that — let me get a team member to help."')),
                ('max_context_messages', models.PositiveIntegerField(default=10, help_text='How many recent messages count as short-term memory')),
                ('memory_summary_trigger_count', models.PositiveIntegerField(default=20, help_text='Regenerate Customer.memory_summary every N new messages')),
                ('business_hours', models.JSONField(blank=True, default=dict, help_text='Optional, used by rules/prompt context', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Rule',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(help_text='Admin label', max_length=200)),
                ('trigger_keywords', models.JSONField(help_text='List of strings; case-insensitive substring match for v1')),
                ('response_text', models.TextField(help_text='What to send when triggered')),
                ('short_circuits_llm', models.BooleanField(default=True, help_text='If True, sends response_text directly and skips the LLM call; if False, folds the rule into the LLM context instead')),
                ('priority', models.IntegerField(default=100, help_text='Lower runs first; first match wins')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['priority'],
            },
        ),
        migrations.CreateModel(
            name='KnowledgeChunk',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=200)),
                ('content', models.TextField(help_text='The actual text the bot can use')),
                ('category', models.CharField(blank=True, help_text='Optional grouping, e.g. "shipping", "returns"', max_length=100)),
                ('embedding', pgvector.django.vector.VectorField(blank=True, dimensions=384, help_text='Regenerated automatically whenever content changes', null=True)),
                ('is_active', models.BooleanField(default=True, help_text='Inactive chunks are excluded from retrieval')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'indexes': [models.Index(fields=['is_active', 'category'], name='knowledge_k_is_acti_c7a101_idx')],
            },
        ),
    ]
