# Generated by Django 5.2.17 on 2026-09-09 12:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('knowledge', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='botsettings',
            name='profile_collection_enabled',
            field=models.BooleanField(default=True, help_text='When on, the bot asks new contacts a short set of travel-profile questions (after its first reply in a new conversation) and files their answers into a customer profile.'),
        ),
        migrations.AddField(
            model_name='botsettings',
            name='profile_intro_message',
            field=models.TextField(blank=True, default='May I have the following information?\n- Name and WhatsApp number?\n- Nationality and country of residence? If you have a GCC residence card, its expiry date too.\n- Approximate travel date?\n- How many days package are you looking for?\n- How many people are travelling together? For children, please share their ages.', help_text="Scripted question sent right after the bot's first reply in a new conversation (requires profile collection to be enabled)."),
        ),
    ]
