# Generated by Django 5.2.17 on 2026-09-10 05:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('knowledge', '0002_botsettings_profile_collection_enabled_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='botsettings',
            name='profile_collection_enabled',
            field=models.BooleanField(default=True, help_text='When on, the bot asks for a short set of travel-profile details once, the first time a visitor shows travel interest, and files their answers into a customer profile.'),
        ),
        migrations.AlterField(
            model_name='botsettings',
            name='profile_intro_message',
            field=models.TextField(blank=True, default='May I have the following information?\n- Name and WhatsApp number?\n- Nationality and country of residence? If you have a GCC residence card, its expiry date too.\n- Approximate travel date?\n- How many days package are you looking for?\n- How many people are travelling together? For children, please share their ages.', help_text='Scripted question list, sent as a second bubble the first time a visitor shows travel intent (requires profile collection to be enabled; leave blank to rely on the AI weaving questions in).'),
        ),
    ]
