# Generated by Django 5.2.11 on 2026-09-04 17:26

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
        ('platforms', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('external_id', models.CharField(help_text='IGSID, PSID, or widget session/visitor ID', max_length=255)),
                ('display_name', models.CharField(blank=True, max_length=255)),
                ('memory_summary', models.TextField(blank=True, help_text='Regenerated periodically by Celery task')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('channel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='customers', to='platforms.channel')),
            ],
        ),
        migrations.CreateModel(
            name='Conversation',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('bot', 'Bot'), ('escalated', 'Escalated'), ('human', 'Human')], default='bot', help_text='Stubbed for future handoff', max_length=20)),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('last_message_at', models.DateTimeField(help_text='Updated on every new message; used for sorting/idle detection')),
                ('assigned_agent', models.ForeignKey(blank=True, help_text='Stubbed for future handoff', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='conversations', to='accounts.agent')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='conversations', to='conversations.customer')),
            ],
            options={
                'ordering': ['-last_message_at'],
            },
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('sender_type', models.CharField(choices=[('customer', 'Customer'), ('bot', 'Bot'), ('agent', 'Agent'), ('system', 'System')], max_length=20)),
                ('content', models.TextField()),
                ('raw_payload', models.JSONField(blank=True, help_text='Original webhook payload, for debugging (dashboard-only)', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('conversation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='conversations.conversation')),
            ],
            options={
                'ordering': ['created_at'],
            },
        ),
        migrations.AddConstraint(
            model_name='customer',
            constraint=models.UniqueConstraint(fields=('channel', 'external_id'), name='unique_channel_external_id'),
        ),
        migrations.AddIndex(
            model_name='message',
            index=models.Index(fields=['conversation', 'created_at'], name='conversatio_convers_4b968d_idx'),
        ),
    ]
