# Generated by Django 6.1.1 on 2026-09-09 06:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('conversations', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='email',
            field=models.EmailField(blank=True, help_text='Provided by the visitor via the widget pre-chat form', max_length=254),
        ),
        migrations.AddField(
            model_name='customer',
            name='phone',
            field=models.CharField(blank=True, help_text='Provided by the visitor via the widget pre-chat form', max_length=50),
        ),
    ]
