# Generated by Django 5.2.17 on 2026-09-10 05:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('conversations', '0002_customer_email_customer_phone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='email',
            field=models.EmailField(blank=True, help_text='Optional; shared by the visitor during chat or entered manually', max_length=254),
        ),
        migrations.AlterField(
            model_name='customer',
            name='phone',
            field=models.CharField(blank=True, help_text='Optional; shared by the visitor during chat or entered manually', max_length=50),
        ),
    ]
