# Generated by Django 5.2.11 on 2026-09-04 17:26

import core.fields
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='LLMConfig',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(help_text='e.g. "Primary — DeepSeek Chat"', max_length=200)),
                ('provider', models.CharField(choices=[('openai_compatible', 'OpenAI-compatible'), ('anthropic', 'Anthropic')], max_length=30)),
                ('api_base_url', models.URLField(blank=True, help_text='Required for openai_compatible (e.g. https://api.deepseek.com/v1); ignored for anthropic')),
                ('api_key', core.fields.EncryptedTextField()),
                ('model_name', models.CharField(help_text='e.g. deepseek-chat, gpt-4o-mini, claude-sonnet-4-6', max_length=200)),
                ('system_prompt', models.TextField(help_text='Base persona/instructions, prepended to every call')),
                ('temperature', models.FloatField(default=0.7)),
                ('max_tokens', models.IntegerField(default=1024)),
                ('is_active', models.BooleanField(default=False, help_text='Only one config can be active at a time')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
