# Generated by Django 5.2.11 on 2026-09-04 17:26

import core.fields
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Channel',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('channel_type', models.CharField(choices=[('instagram', 'Instagram'), ('messenger', 'Messenger'), ('wordpress', 'WordPress')], max_length=20)),
                ('name', models.CharField(help_text='Admin-facing label, e.g. "Main IG Account"', max_length=200)),
                ('credentials', core.fields.EncryptedJSONField(blank=True, default=dict)),
                ('is_active', models.BooleanField(default=True, help_text='Whether the bot responds on this channel')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'channel',
                'verbose_name_plural': 'channels',
            },
        ),
    ]
