# Generated by Django 6.1 on 2026-09-15 11:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('platforms', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='channel',
            name='channel_type',
            field=models.CharField(choices=[('instagram', 'Instagram'), ('messenger', 'Messenger'), ('whatsapp', 'WhatsApp'), ('wordpress', 'WordPress')], max_length=20),
        ),
    ]
